Bump net-ssh version for Rails LTS branch...
Not sure how clipped extension uses net-ssh and if this broke it, but needed to update net-ssh in my project Gemfile in order to get Capistrano working again
cap deploy was throwing this:

*** [deploy:update_code] rolling back
  * executing "rm -rf /home/nzffa-staging-app/production/releases/20210727142423; true"
    servers: ["c.pool.nzffa.org.nz"]
/home/jomz/Development/nzffa/vendor/bundle/ruby/2.7.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67: warning: Object#timeout is deprecated, use Timeout.timeout instead.
/home/jomz/Development/nzffa/vendor/bundle/ruby/2.7.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84: warning: Object#timeout is deprecated, use Timeout.timeout instead.
/home/jomz/Development/nzffa/vendor/bundle/ruby/2.7.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/cipher_factory.rb:98: warning: constant OpenSSL::Cipher::Cipher is deprecated
 ** [deploy:update_code] exception while rolling back: Capistrano::ConnectionError, connection failed for: c.pool.nzffa.org.nz (NoMethodError: undefined method `p=' for #<OpenSSL::PKey::DH:0x00007fa3000107c0>
 ** [deploy:update_code] Did you mean?  p)
connection failed for: c.pool.nzffa.org.nz (NoMethodError: undefined method `p=' for #<OpenSSL::PKey::DH:0x000055f277f90320>
Did you mean?  p)